spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 90s

server:
  shutdown: graceful
  task-executor:
    thread-pool-size:
      core: ${TASK_EXECUTOR_THREAD_CORE_POOL_SIZE:200}
      max: ${TASK_EXECUTOR_THREAD_MAX_POOL_SIZE:200}
    await-termination-seconds: ${TASK_EXECUTOR_AWAIT_TERMINATION_SECONDS:90}
  tomcat:
    threads:
      min-spare: ${TOMCAT_THREADS_MIN_SPARE:100}
